name: Update IPTV List
on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yt-dlp
        run: pip install yt-dlp
      - name: Run Generator
        run: python update_list.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add channels.m3u
          git commit -m "Update playlist" || exit 0
          git push
